"""create_outreach_and_replies_tables

Revision ID: 40af0b9db472
Revises: 
Create Date: 2026-04-21 14:45:26.469943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40af0b9db472'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('role_context', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('awaiting_reply', 'replied', 'archived', name='outreachstatus', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outreach_recipient_email', 'outreach', ['recipient_email'], unique=False)
    op.create_table('replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outreach_id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('classification', sa.Enum('interested', 'not_interested', 'needs_followup', 'unclassified', name='classification', native_enum=False), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_reasoning', sa.Text(), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outreach_id'], ['outreach.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_message_id')
    )
    op.create_index('ix_replies_gmail_message_id', 'replies', ['gmail_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_replies_gmail_message_id', table_name='replies')
    op.drop_table('replies')
    op.drop_index('ix_outreach_recipient_email', table_name='outreach')
    op.drop_table('outreach')
    # ### end Alembic commands ###
